version: "3.8"
services:
    nubank-sync-ynab:
        build: .
    generate:
        build: .
        entrypoint: python /usr/local/lib/python3.6/site-packages/nubank_sync_ynab/generate.py
        volumes: 
            - /tmp/nubank_sync_ynab:/tmp/nubank_sync_ynab